package com.example.platepal.data

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp

/* Data class that represents the PhotoMeta Document Collection in Firestore
    imageTitle: Title of image
    imageType: Type of image
    recipeDocumentId: References the Firestore Document Id for the related Recipe
    sourceType: Defines where the metadata is sourced from (e.g., user, api, etc.)
    sourceId: Specifies the sourceId from the source system
    timeStamp: Written on the Firestore server
    firestorageId: firestoreId is generated by Firestore, used as primary key
 */
data class PhotoMeta (
    var imageTitle: String = "",
    var imageType: String = "",
    var recipeDocumentId: String = "",
    var sourceType: String = "",
    var sourceId: String = "",
    @ServerTimestamp
    val timeStamp: Timestamp? = null,
    @DocumentId
    var firestoreId: String = ""
)