package com.example.platepal.data

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import java.io.Serializable

/* Data class that represents the RecipeMeta Document Collection in Firestore
    title: title of Recipe
    externalId: external Id of this recipe.  If sourced internally by user this attribute can be
        blank
    timeStamp: Written on the Firestore server
    firestorageId: firestoreId is generated by Firestore, used as primary key
 */
data class RecipeMeta (
    var sourceId: String = "",
    var title: String = "",
    var image: String = "",
    var imageType: String = "",
    var createdBy: String = "",
    @ServerTimestamp
    val timeStamp: Timestamp? = null,
    @DocumentId
    var firestoreId: String = ""
): Serializable {
    override fun equals(other: Any?) : Boolean =
        if (other is RecipeMeta) {
            sourceId == other.sourceId
        } else {
            false
        }

    override fun hashCode(): Int {
        var result = sourceId.hashCode()
        result = 31 * result + title.hashCode()
        result = 31 * result + image.hashCode()
        result = 31 * result + imageType.hashCode()
        return result
    }
}