package com.example.platepal.data

import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import java.io.Serializable
import com.google.firebase.firestore.ServerTimestamp

data class UserMeta(
    var fullName: String = "",
    var email: String = "",
    var uid: String = "",
    var pictureUUID: String = "",
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId
    var firestoreID: String = ""
): Serializable



